security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chainprovider:
            chain:
                providers: [fos_userbundle, fos_facebook_provider]
        fos_facebook_provider:
            id: fos_facebook.user.login
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/

            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~

            fos_facebook:
                app_url: ""
                server_url: "http://%site_domain%"
                login_path: /login
                check_path: /facebook/login_check
                default_target_path: fos_user_profile_edit
                provider: fos_facebook_provider

            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: /user/login_check
                login_path: /user/login
                remember_me: true
            logout:       
                path: /user/logout 
            anonymous:    true

    access_control:
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/, role: IS_AUTHENTICATED_FULLY }
        
        - { path: ^/secured/.*, role: [IS_AUTHENTICATED_FULLY] }
        - { path: ^/.*, role: [IS_AUTHENTICATED_ANONYMOUSLY] }