victorvis_user_homepage:
    pattern:  /
    defaults: { _controller: VICTORVISUserBundle:Default:index }
    
victorvis_login_facebook:
    pattern:  /login_facebook
    defaults: { _controller: VICTORVISUserBundle:Default:facebookLogin }