parameters:
##
    
services:
    fos_facebook.user.login:
        class: VICTORVIS\UserBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            container: "@service_container"
            dispatcher: "@event_dispatcher"
            formFactory: "@fos_user.registration.form.factory"

    victorvis_user.user_manager:
        class: VICTORVIS\UserBundle\Security\User\Manager\UserManager
        arguments: ["@security.encoder_factory", "@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.entity_manager", %user.class%, "@service_container"]

    victorvis_user.registration.form.type:
        class: VICTORVIS\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: victorvis_user_registration }

    victorvis_user.profile.form.type:
        class: VICTORVIS\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: victorvis_user_profile }

    victorvis_user.resetting.form.type:
        class: VICTORVIS\UserBundle\Form\Type\ResettingFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: victorvis_user_resetting }

    victorvis_user.profile_edit:
        class: VICTORVIS\UserBundle\EventListener\ProfileEditListner
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }
            
    victorvis_user.security.interactive_login_listener:
        class: VICTORVIS\UserBundle\EventListener\InteractiveLoginListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_listener,  event: security.interactive_login, method: onSecurityInteractiveLogin, priority: 255 }