parameters:
#    victorvis_admin.example.class: VICTORVIS\AdminBundle\Example

services:
#    victorvis_admin.example:
#        class: %victorvis_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
